---

- name: Run cfg commands on routers
  hosts: 192.168.100.1
  gather_facts: false
  connection: local

  tasks:

    - name: Config password encryption
      ios_config:
        diff_against: startup
        diff_ignore_lines:
          - description .*
          - alias .*
        provider: "{{ cli }}"

