---

- name: Run show commands on routers
  hosts: cisco-switches
  gather_facts: false
  connection: local

  tasks:

    - name: Run sh cdp neighbors detail
      ntc_show_command:
        connection: ssh
        platform: "cisco_ios"
        command: "sh cdp neighbors detail"
        host: "{{ inventory_hostname }}"
        username: "cisco"
        password: "cisco"
        template_dir: "library/ntc-ansible/ntc-templates/templates"
      register: result

    - name: Copy facts to files
      copy:
        content: "{{ result.response | to_nice_yaml }}"
        dest: "all_facts/{{inventory_hostname}}_sh_cdp.yml"
